# [[main]]
#     name = "Team"
#     url = "/team"
#     weight = 1

[[main]]
    name = "Network"
    url = "/"
    weight = 1

[[main]]
    name = "Team"
    url = "/teams"
    weight = 2

[[main]]
    name = "Docs"
    url = "https://docs.hashed.network"
    weight = 3

# [[main]]
#     name = "Launch"
#     url = "/launch"
#     weight = 3

# [[main]]
#     name = "Subscribe"
#     url = "/subscribe"
#     weight = 4
#     [main.params]
#         last = true

# [[button]]
#     name = "Get in touch"
#     url = "/touch"
#     weight = 1


 [[social]]
     name = 'Medium'
     url = 'https://medium.com/@hashednetwork'
     weight = '1'
     [social.params]
         icon = 'icons/medium.svg'

[[social]]
    name = 'Twitter'
    url = 'https://twitter.com/@HashedNetwork'
    weight = '2'
    [social.params]
        icon = 'icons/twitter.svg'
        
[[social]]
    name = 'GitHub'
    url = 'https://github.com/hashed-io'
    weight = '3'
    [social.params]
        icon = 'icons/github.svg'


[[footer]]
    name = "Network"
    url = "/"
    weight = 1
[[footer]]
    name = "team"
    url = "/categories"
    weight = 2
[[footer]]
    name = "Docs"
    url = "https://docs.hashed.network"
    weight = 3
# [[footer]]
#     name = "Team"
#     url = "/team"
#     weight = 2

# [[footer]]
#     name = "Docs"
#     url = "/docs"
#     weight = 3

# [[footer]]
#     name = "Launch"
#     url = "/launch"
#     weight = 4

# [[footer]]
#     name = "Subscribe"
#     url = "/subscribe"
#     weight = 5