title = 'Hashed Network'
description = 'Hashed network enables the full business lifecycle for digitally-native organizations and web3-curious businesses seeking benefits of decentralized digital economies.'
titleSeparator = '|'
thumbnail = 'images/logo.png'